### ISSUE TITLE
Regular Season Standings orientation flipping

### ISSUE THREAD

**Issue by MicahWW** [MicahWW/NHL_Dashboards#14]
In the Regular Season Standings the below lines of code are used to switch the layout from a portrait to landscape orientation, and vice versa, but that isn't needed.

https://github.com/MicahWW/NHL_Dashboards/blob/0d052e1d19907679ad2ae7852d0786c46517cbbf/Views/RegularSeason/Standings.cshtml#L115-L132

Instead, the built-in CSS media query should be used. This will make the code more readable and less complex. EX:
```CSS
/* Styles for portrait orientation */
@media (orientation: portrait) {
    body {
        width: 100%
    }
}

/* Styles for landscape orientation */
@media (orientation: landscape) {
    body {
        height: 100%
    }
}
```
